name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Build (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake make g++
        sudo apt-get install -y libvulkan-dev xorg-dev
        sudo apt-get install -y glslang-tools
        sudo apt-get install -y libfmt-dev
        sudo apt-get install -y libcurl4-openssl-dev
        git submodule update --init --recursive
        cd build
        sudo bash ./build.sh

    - name: Setup Python (windows-latest)
      if: matrix.os == 'windows-latest'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PyInstaller (windows-latest)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install Vulkan SDK (windows-latest)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        $version = "1.3.275.0"
        $installer = "VulkanSDK-$version-Installer.exe"
        $url = "https://sdk.lunarg.com/sdk/download/$version/windows/$installer"
        Invoke-WebRequest -Uri $url -OutFile $installer
        Start-Process -FilePath .\$installer -ArgumentList "--accept-licenses --default-answer --confirm-command install" -Wait
        $sdkPath = "C:\VulkanSDK\$version"
        echo "VULKAN_SDK=$sdkPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "$sdkPath\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build (windows-latest)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        git submodule update --init --recursive
        cd build
        build.bat
