name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Build (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake make g++
        sudo apt-get install -y libvulkan-dev xorg-dev
        sudo apt-get install -y glslang-tools
        sudo apt-get install -y libfmt-dev
        sudo apt-get install -y libcurl4-openssl-dev
        git submodule update --init --recursive
        cd build
        sudo bash ./build.sh

    - name: Setup Python (windows-latest)
      if: matrix.os == 'windows-latest'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PyInstaller (windows-latest)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Install Vulkan SDK (windows-latest)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        choco install vulkan-sdk -y

    - name: Build (windows-latest)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        git submodule update --init --recursive
        cd build
        build.bat
